### ISSUE TITLE
raceback (most recent call last):   File "app.py", line 3, in <module>     from web.wsgiserver import CherryPyWSGIServer ImportError: No module named wsgiserver

### ISSUE THREAD

**Issue by mkampo** [dineshshetty/Android-InsecureBankv2#17]
Hello! I downloaded the .zip file for the Insecure Banking App and I am trying to set up server. After the pip install -r requirements.txt, I get no errors. But after the command python app.py I get the following error:"Traceback (most recent call last):   File "app.py", line 3, in <module>     from web.wsgiserver import CherryPyWSGIServer ImportError: No module named wsgiserver". Is it something wrong with cherrypy?

**Comment by Manoj-Madushantha** [comment]
SAME ISSUE HERE. DOWNGRADE CHERRYPY to 5.1.0. BUT PROBLEM REMAIN SAME.

$ python app.py
Traceback (most recent call last):
  File "app.py", line 3, in <module>
    from web.wsgiserver import CherryPyWSGIServer
ImportError: No module named wsgiserver

**Comment by Ravana-Astra** [comment]
> SAME ISSUE HERE. DOWNGRADE CHERRYPY to 5.1.0. BUT PROBLEM REMAIN SAME.
> 
> $ python app.py
> Traceback (most recent call last):
> File "app.py", line 3, in
> from web.wsgiserver import CherryPyWSGIServer
> ImportError: No module named wsgiserver

I have the same problem!! 
can anyone guide me??

**Comment by osmooth** [comment]
I solved this by installing 
python -m pip install web.py==0.37
not sure if the requirements have been met correctly.

**Comment by dineshshetty** [comment]
Should be fixed now.

**Comment by trucphamtrung** [comment]
I still have this issue. I follow @osmooth 's guide and it works.

**Comment by jriverab** [comment]
> I solved this by installing
> python -m pip install web.py==0.37
> not sure if the requirements have been met correctly.

followed your advice and worked magically! Thank you sir!

**Comment by mrtouch93** [comment]
You need to modify the line 3 of app.py from
`from web.wsgiserver import CherryPyWSGIServer`
to
`from cheroot.wsgi import Server as CherryPyWSGIServer`

For me it worked.

**Comment by leoandrade20** [comment]
I solved this with 
`from cheroot.wsgi import Server as CherryPyWSGIServer`

**Comment by leoandrade20** [comment]
I solved this changing 
` from web.wsgiserver import CherryPyWSGIServer`
to
`from cheroot.wsgi import Server as CherryPyWSGIServer`

**Comment by jasmeetsingh001** [comment]
Guy's Follow this video and setup this in Windows: https://www.youtube.com/watch?v=DC2PnV2QD4c
100% Working, as above method might not working in mine case but this video helped me alot!
Try this and must comment me if it's working!

**Comment by BeneInfosec** [comment]
> I solved this by installing
> python -m pip install web.py==0.37
> not sure if the requirements have been met correctly.

Worked for me

**Comment by ricotomax** [comment]
solved this by 
`pip install --upgrade cheroot`
having the below in the requirements.txt file
`from cheroot import wsgi`
